### ISSUE TITLE
pgadmin4 1.11.0 - Cant login

### ISSUE THREAD

**Issue by rosscdh** [rowanruseler/helm-charts#161]
**Describe the bug**
Deploy the helm chart with valid secret and email set but not able to log in with those settings

**Which chart**:
pgadmin4 1.11.0

**What happened**:
Unable to login using the set user/pass

**What you expected to happen**:
able to login using the set user/pass

**Anything else we need to know**:
![Screenshot 2022-08-01 at 11 31 21](https://user-images.githubusercontent.com/397106/182118846-1f72d3b4-b082-4799-9a49-dbbf99c227a7.png)

**Comment by felix-mos** [comment]
+1

**Comment by Pflegusch** [comment]
I've also encountered this problem but I could fix it if you specify an email (must be an email, even tho there is a comment stating it can be nickname too) in ``env.email`` and password in ``env.password``. The default values somehow don't seem to work. After that, delete the content in the persistent volume and upgrade the chart (or completely reinstall it). This is important because otherwise it will use the old email and password from the pv. After that it worked for me

**Comment by behoof4mind** [comment]
This should help https://github.com/rowanruseler/helm-charts/pull/177
