### ISSUE TITLE
Helm chart repo inaccessible via Artifactory

### ISSUE THREAD

**Issue by MHenn1g** [rowanruseler/helm-charts#194]
Hi, you had kind of a similar issue in https://github.com/rowanruseler/helm-charts/issues/171#issue-1400560712

At least I hope my problem is related to the fact that opening the repo via browser and without adding the index.yaml part throws the 404:

> Helm chart repo at https://helm.runix.net/ returns 404. ![image](https://user-images.githubusercontent.com/27248144/194459805-1749b6ce-01bf-4953-bf94-b91e7b5db326.png)

Currently I am trying to utilize the repo as a remote repository in Artifactory...for testing purposes I added the elastic repo as well as the runix repo:
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/6153958/217565945-648b4f3d-1cc7-4ab2-9104-d6d6b2006cab.png">

Despite the fact that both have been added in a similar fashion the elastic repo works fine, while no fetch from runix may be performed. And it throws this nice error:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/6153958/217560030-73a253db-1560-490d-8374-037032bcdda2.png">

Which is why I hope the problem is related to https://github.com/rowanruseler/helm-charts/issues/171#issue-1400560712

Could you please have a look into the 404

**Comment by rowanruseler** [comment]
This is a repository, you can add it with: `helm repo add runix https://helm.runix.net`

I never tested it on artifactory, it is technically just a github page. You can view the github pages here: https://github.com/rowanruseler/helm-charts/tree/gh-pages

So what happens when you add this url: https://github.com/rowanruseler/helm-charts/blob/gh-pages/index.yaml

**Comment by rowanruseler** [comment]
glad it worked out!
