### ISSUE TITLE
Fatal error network policy

### ISSUE THREAD

**Issue by ElfoLiNk** [rowanruseler/helm-charts#28]
**Describe the bug**
`FATA: 2020/05/29 13:45:29.801809 add network policy: named ports in network policies is not supported yet. Rejecting network policy: pgadmin-pgadmin4 from further processing. named port http in network policy`

https://github.com/weaveworks/weave/issues/3785

**Version of Helm and Kubernetes**:
Helm 2
Kubernetes 1.14
Weave 2.6

**Which chart**:
pgadmin4

**Comment by rowanruseler** [comment]
@ElfoLiNk thank you for bringing this to my attention.

I am not sure if weave will fix this, since the comments on the issue you linked are talking about just adjusting the fatal to an error. However, the error message displays 'not supported yet'. So that is pretty confusing.

Just for my understanding, if you release pgadmin4 within the values.yaml file all defined `http` with 80, does it function? Or am I missing some ports to be configurable?

**Comment by david972** [comment]
I've done a test and yes set `service.targetPort: 80` works

**Comment by rowanruseler** [comment]
Good to hear that if you set that, it works for you @david972

**Comment by utkuozdemir** [comment]
I think the NetworkPolicy should be put behind an `enabled` flag for the use cases that do not need it at all.

**Comment by rowanruseler** [comment]
The error message and the link provided by @ElfoLiNk is pretty clear, the solution is adjusting the values file with: `service.targetPort: 80`. Since not everybody uses weave I'll keep to original value on `http`. The error message is clear enough to quickly figure out the solution.

You are welcome to open up a pull request with perhaps a comment above `service.targetPort` explaining the resolution to this issue.

**Comment by utkuozdemir** [comment]
Note that I have faced the same issue with Cilium, not Weave.

**Comment by rowanruseler** [comment]
@utkuozdemir but I assume setting it to `80` resolved your issue?

**Comment by utkuozdemir** [comment]
Yes that's right. Just wanted to share that the issue is not only specific to Weave.

**Comment by rowanruseler** [comment]
@utkuozdemir somebody was nice enough to open a PR with the solution: https://github.com/rowanruseler/helm-charts/pull/49
