### ISSUE TITLE
`ingress.path` not taken into account

### ISSUE THREAD

**Issue by MatthiasLohr** [rowanruseler/helm-charts#7]
The documentation table mentions `ingress.path`, but this variable is not used in the ingress template.

Best regards
Matthias

**Comment by rowanruseler** [comment]
Ah, I've written the README wrong, because it is .ingress.hosts.paths. I'll adjust it, thanks!

I hope this resolved your issue?

**Comment by MatthiasLohr** [comment]
No really. Doesn't work with paths != "/". Also, in my opinion, it's questionable if you really need hosts/paths for a single application like pgadmin.

I would like to improve it, but since you have this multi chart single repo approach, instead of forking I decided to write my own chart, which works completely. If you want, we can combine our effort there.

**Comment by rowanruseler** [comment]
You are correct, but it is the default ingress that everybody is used to who ever works with helm charts. So I dislike to go away from the default setup.

The reason it is in 'this multi chart sing repo approach', is because I am planning on hosting more charts. Plus it is handy, to pull the chart from a repo :)


No thanks, rather have the chart in my own repo, or merge it into a bigger repo.
